### ISSUE TITLE
当在子viewController里添加UITableView的时候，tableView上下滑动时全部的cell都消失了

### ISSUE THREAD

**Issue by czy8187** [Herbert77/HHSlideView#1]
- (NSArray *)childViewControllersInSlideView:(HHSlideView *)slideView;方法里添加子viewController,子viewController里[self.view addSubview:tableView];或者子viewController继承UITableViewController都会有这种情况。滑动或者点击cell，tableView的cell都会消失。请问有遇到过吗？问题如何定位呢？

**Comment by Herbert77** [comment]
你好，我在最新版本中修复了这个Bug. 过程是这样的，由于所有的子viewController被代理方法作为数组传入 hhslideView, 但是在 hhslideView 中， 我的子控制器数组是一个局部变量，没有在 hhslideView 的生命周期中持有所有子控制器，当视图都被添加上去后，子控制器对象已经被释放，导致了这个Bug.
感谢支持，欢迎指出问题！
