### ISSUE TITLE
how to set textcolor of item ?

### ISSUE THREAD

**Issue by davamp** [Herbert77/HHSlideView#2]

**Comment by Herbert77** [comment]
Hi, I have added two delegate methods.

**Comment by Herbert77** [comment]
Hi, I have added two delegate methods in latest version. As below:

- (UIColor *)colorOfSlideItemsTitle:(HHSlideView *)slideView;
- (UIColor *)colorOfHighlightedSlideItemsTitle:(HHSlideView *)slideView;

These methods can solve the problem. 
Thanks for advice! ~

**Comment by davamp** [comment]
nice man !! what about the swipe gesture ?

**Comment by Herbert77** [comment]
You can swipe the contentView to change slideItems.  ；）

**Comment by davamp** [comment]
Well ok thanks man

**Comment by Herbert77** [comment]
You are welcome.  O(∩_∩)O~~
